title: Ding Runjie's Homepage
page-top-title: Ding Runjie
top-section-bg-text: Computer Science
home-subtitle: Ding Runjie&ensp;|&ensp;丁润杰
copyright-text: '&copy; Ding Runjie 2023-2024. All Rights Reserved.'
